apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mongodb-express-ingress
spec:
  tls:
  - hosts:
    - express.beyond2025.cloud
    secretName: express.beyond2025.cloud
  rules:
  - host: express.beyond2025.cloud
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: mongodb-express-service
            port: 
              number: 8081